/** @type {import('tailwindcss').Config} */
// Tokens mirrored from stitch_fittrack_fitness_web_app/kinetic_performance_system/DESIGN.md
// so that markup lifted from the design files renders unchanged.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#dae2fd',
        'on-primary-fixed': '#390c00',
        primary: '#ab3600',
        'on-tertiary-fixed-variant': '#38485d',
        'secondary-fixed': '#dae2fd',
        surface: '#f7f9fb',
        'surface-tint': '#ab3600',
        'on-primary-container': '#561700',
        'surface-container': '#eceef0',
        'surface-variant': '#e0e3e5',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'tertiary-container': '#8595ad',
        'on-tertiary-fixed': '#0b1c30',
        'surface-dim': '#d8dadc',
        'surface-container-highest': '#e0e3e5',
        'on-surface-variant': '#5b4138',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#bec6e0',
        'inverse-surface': '#2d3133',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#ffb59c',
        'on-surface': '#191c1e',
        'on-primary-fixed-variant': '#832700',
        'on-tertiary-container': '#1d2e42',
        background: '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'primary-container': '#ff5f1f',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'on-error': '#ffffff',
        'outline-variant': '#e3bfb3',
        'on-secondary-fixed': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#ffb59c',
        'on-secondary-container': '#5c647a',
        error: '#ba1a1a',
        'primary-fixed': '#ffdbcf',
        'inverse-on-surface': '#eff1f3',
        outline: '#8f7066',
        'on-secondary-fixed-variant': '#3f465c',
        tertiary: '#505f76',
        'tertiary-fixed-dim': '#b7c8e1',
        'surface-bright': '#f7f9fb',
        'on-secondary': '#ffffff',
        secondary: '#565e74',
        'tertiary-fixed': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        sm: '8px',
        gutter: '16px',
        xs: '4px',
        'margin-mobile': '16px',
        lg: '24px',
        'margin-desktop': '40px',
        base: '4px',
        md: '16px',
      },
      fontFamily: {
        'display-stat': ['Montserrat', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-stat': ['48px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
